# Uncomment this line to define a global platform for your project
  platform :ios, ‘8.0’
# Uncomment this line if you're using Swift
# use_frameworks!

target 'NPushMail' do
    
pod 'MKNetworkKit', '~> 0.87'
pod 'BBSZLib', '~> 0.0.2'
pod 'QBImagePickerController', '~> 2.5.2'
pod 'JDStatusBarNotification', '~> 1.5.2'
pod 'SDWebImage', '~> 3.7.3'
pod 'AFNetworking', '~> 2.6.1'
pod 'AFNetworkActivityLogger', '~> 2.0.4'
pod 'MJRefresh', '~> 2.4.12'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'FMDB', '~> 2.5'
pod 'KVOController', '~> 1.0.3'
pod 'CocoaLumberjack', '~> 2.2.0'
pod 'OpenUDID', '~> 1.0.0'
pod 'MGSwipeTableCell', '~> 1.5.3'
pod 'UMengAnalytics-NO-IDFA', '~> 4.1.1'
pod 'SocketRocket', '~> 0.4.2'
pod 'RSKImageCropper', '~> 1.5.1'
pod 'IDMPhotoBrowser', '~> 1.8.4'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
pod 'CustomIOSAlertView', '~> 0.9.3'
pod 'TYAttributedLabel', '~> 2.6.0'
pod 'TDBadgedCell', '~> 2.6'
pod 'MQTTClient', :git => 'https://gaoyongqing@bitbucket.org/mailchat/mqtt-client-framework.git'
pod 'AppAuth', :git => 'https://gaoyongqing@bitbucket.org/mailchat/appauth.git'

end

target 'MailChatTests' do

pod 'CocoaLumberjack', '~> 2.2.0'
pod 'UMengAnalytics-NO-IDFA', '~> 4.1.1'


end

